
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: ibm
    password: ibm
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true 


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      defaultZone: http://localhost:8101/eureka
      
zipkin:
    base-url: http://localhost:9411/
    
sleuth:
    smapler:
      probability: 1.0
    trace-id128: true